// apps/website2/src/components/Header.tsx
import "./Header.css";
import { useLocation } from 'preact-iso';
import DownloadButton from './DownloadButton';

export function Header() {
	const { url } = useLocation();

	return (
		<header>
            <div class="content-wrapper">
                <img src="./src/assets/icon-color.svg" width="300" height="300" />&nbsp;<span>Trilium Notes</span>

                <nav>
                    <a href="/" class={url == '/' && 'active'}>
                        Home
                    </a>
                    <a href="/404" class={url == '/404' && 'active'}>
                        404
                    </a>
                </nav>

                <DownloadButton />
            </div>
		</header>
	);
}

// apps/website/src/routes/header.svelte
<header class="header bg-white sticky top-0 z-50">
    <div class="container mx-auto flex items-center py-5">
        <a href="/" class="flex items-center gap-x-2 w-100">
            <img src="icon-color.svg" alt="Trilium Notes Logo" class="w-10 h-10">
            <span class="text-xl">Trilium Notes</span>
        </a>

        <div class="group w-full">
            <nav class="header-nav">
                <ul class="flex items-center justify-end gap-4">
                    <li><a href="/">Home</a></li>
                    <li><a href="/about">About</a></li>
                    <li><a href="/services">Services</a></li>
                    <li><a href="/contact">Contact</a></li>
                </ul>
            </nav>
        </div>
    </div>
</header>
